config/routes.rb
Rails.application.routes.draw do
  root  to: 'static_pages#info'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
#  get 'sessions/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
# info
  get '/info/modify', to: 'static_pages#modify'
  post '/info/update', to: 'static_pages#update'
  get '/info/create_form', to: 'static_pages#create_form'
  post '/info/info_create', to: 'static_pages#info_create'
  get '/info/update_form', to: 'static_pages#update_form'
  post '/info/update_form', to: 'static_pages#update_form'
  post '/info/info_update', to: 'static_pages#info_update'
  delete '/info/destroy', to: 'static_pages#info_destroy'
#datainsert
  get '/datainsert', to: 'quiz_data_insert#index'
  post '/datainsert/exec', to: 'quiz_data_insert#insert'
# course
  get '/course', to: 'course#top'
  post '/course', to: 'course#update'
  get '/result', to: 'course#last'
  post '/show', to: 'course#show'
# choose course
  get '/choose_course', to: 'choose_course#index'
  get '/choose_course/get_num', to: 'choose_course#get_num'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:password, :password_cinfirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div>
    <%= form_for(@user, url:password_reset_path(params[:id])) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= hidden_field_tag :email, @user.email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Update password" %>
    <% end %>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<%= form_for(:password_reset, url: password_resets_path) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.submit "Submit" %>
<% end %>