config/routes.rb
Rails.application.routes.draw do
  root  to: 'static_pages#info'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
#  get 'sessions/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
# info
  get '/info/modify', to: 'static_pages#modify'
  post '/info/update', to: 'static_pages#update'
  get '/info/create_form', to: 'static_pages#create_form'
  post '/info/info_create', to: 'static_pages#info_create'
  get '/info/update_form', to: 'static_pages#update_form'
  post '/info/update_form', to: 'static_pages#update_form'
  post '/info/info_update', to: 'static_pages#info_update'
  delete '/info/destroy', to: 'static_pages#info_destroy'
#datainsert
  get '/datainsert', to: 'quiz_data_insert#index'
  post '/datainsert/exec', to: 'quiz_data_insert#insert'
# course
  get '/course', to: 'course#top'
  post '/course', to: 'course#update'
  get '/result', to: 'course#last'
  post '/show', to: 'course#show'
# choose course
  get '/choose_course', to: 'choose_course#index'
  get '/choose_course/get_num', to: 'choose_course#get_num'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/choose_course_controller.rb
require("./app/controllers/controllers_g_var.rb")
class ChooseCourseController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    @labels_ja = []
    Label.all.each do |ld|
      @labels_ja << $name_trans[ld.name]
    end
  end

  def get_num
    render partial: 'select_num', locals: { label_name: $name_trans[params[:label_name]] }
  end

  private
    def make_q_types
      types = ["5choice", "enterybox"]
      flag = Label.find(params[:label]).q_types #q_typesがbitflagになっているので
      for i in 0...types.size
        if(flag % 2 == 1)
          q_types << types[i]
        end
        flag = (flag / 2).to_i
      end
      return q_types
    end

    #ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

end

app/helpers/choose_course_helper.rb
module ChooseCourseHelper
end

app/views/choose_course/_select_num.html.erb
<%= select_tag :num, options_for_select([*1..(Label.find_by(name: label_name).max)]), class: "form-control" %>

app/views/choose_course/index.html.erb
<p>
    問題を選択(現在は4択問題のみ)
    <%= form_tag(course_path, method: :get) do  %>
      <div id="label_area" >
        <%= select_tag :label_name, options_for_select([*@labels_ja]), class: "form-control" %>
      </div>
      <div id="num_area" >
        <%= render partial: 'select_num', locals: {label_name: Label.first.name} %>
      </div>
      <%= submit_tag("問題へ", class: "btn btn-primary") %>
    <% end %>
</p>