config/routes.rb
Rails.application.routes.draw do
  root  to: 'static_pages#info'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
#  get 'sessions/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
# info
  get '/info/modify', to: 'static_pages#modify'
  post '/info/update', to: 'static_pages#update'
  get '/info/create_form', to: 'static_pages#create_form'
  post '/info/info_create', to: 'static_pages#info_create'
  get '/info/update_form', to: 'static_pages#update_form'
  post '/info/update_form', to: 'static_pages#update_form'
  post '/info/info_update', to: 'static_pages#info_update'
  delete '/info/destroy', to: 'static_pages#info_destroy'
#datainsert
  get '/datainsert', to: 'quiz_data_insert#index'
  post '/datainsert/exec', to: 'quiz_data_insert#insert'
# course
  get '/course', to: 'course#top'
  post '/course', to: 'course#update'
  get '/result', to: 'course#last'
  post '/show', to: 'course#show'
# choose course
  get '/choose_course', to: 'choose_course#index'
  get '/choose_course/get_num', to: 'choose_course#get_num'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EStud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <header>
    <div class="container">
      <nav class="navbar navbar-expand-ms navbar-light">
        <%= link_to "E-Stud", root_path, class: "navbar-brand" %>
        
        <% if logged_in? %>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div id="menu" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><%= link_to "Account", choose_course_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Profile", current_user, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Settings", edit_user_path(current_user), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %></li>
              <% if current_user.admin? && current_user?(current_user) %>
                <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
              <% end %>
            </ul>
          </div>
        <% else %>
          <div class="login">
            <ul class="ml-auto navbar-nav">
              <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
            </ul>
          </div>
        <% end %>
      </nav>
    </div>
    <div class="mb-4"></div>
  </header>

  <body>
    <div class="container">
      <% if flash %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-info"><%= message %></div>
        <% end %>
      <% end %>
    <%= yield %>
    </div>
  </body>

  <footer>
    <div class="container mt-4">
      <ul class="list-inline float-right">
        <li class="list-inline-item"><%= link_to "About", about_path %></li>
        <li class="list-inline-item"><%= link_to "Contact", contact_path %></li>
      </ul>
    </div>
  </footer>
</html>